apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger-service
  template:
    metadata:
      labels:
        app: logger-service
    spec:
      containers:
        - name: logger-service
          image: "andrelmm91/go-http:logger-service-v1"
          ports:
            - containerPort: 80
            - containerPort: 5001
            - containerPort: 50001
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: logger-service
spec:
  selector:
    app: logger-service
  type: ClusterIP
  ports:
    - name: web-port
      protocol: TCP
      port: 80
      targetPort: 80
    - name: rpc-port
      protocol: TCP
      port: 5001
      targetPort: 5001
    - name: grpc-port
      protocol: TCP
      port: 50001
      targetPort: 50001
