apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - name: mailhog
          image: "mailhog/mailhog:latest"
          ports:
            - containerPort: 1025
            - containerPort: 8025
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
spec:
  selector:
    app: mailhog
  type: ClusterIP
  ports:
    - name: mailhog-port1
      protocol: TCP
      port: 1025
      targetPort: 1025
    - name: mailhog-port2
      protocol: TCP
      port: 8025
      targetPort: 8025
